app:
  name: bilio-backend
  env: development
  port: 8080
server:
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 120s
database:
  url: "postgresql://user:password@localhost:5432/bilio?schema=public"
logging:
  level: info
